# Generated by Django 2.2.4 on 2019-08-13 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblog',
            name='myblog_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_text', models.TextField()),
                ('comments_myblog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.myblog')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
