# Generated by Django 2.2.4 on 2019-08-13 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20190813_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myblog',
            old_name='myblog_date',
            new_name='article_date',
        ),
        migrations.RenameField(
            model_name='myblog',
            old_name='myblog_likes',
            new_name='article_likes',
        ),
        migrations.RenameField(
            model_name='myblog',
            old_name='myblog_text',
            new_name='article_text',
        ),
        migrations.RenameField(
            model_name='myblog',
            old_name='myblog_title',
            new_name='article_title',
        ),
    ]
